version: '3.10'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - ./media:/app/media
      - ./static:/app/static

  db:
    image: postgres:13.0-alpine
    env_file:
      - .env
    volumes:
      - drugs_db:/var/lib/postgresql/data

volumes:
  drugs_db:
  static_data:
  postgres_data: