# Generated by Django 4.2.7 on 2023-11-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('released', models.DateField()),
                ('diseases', models.ManyToManyField(to='drugs.disease')),
            ],
        ),
    ]
