# Generated by Django 4.2.7 on 2023-11-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_alter_drug_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='released',
            field=models.DateField(default='2023-06-01'),
        ),
    ]
